### ISSUE TITLE
Nuxt context not available in actions

### ISSUE THREAD

**Issue by alexcroox** [vedmant/nuxt3-vuex#15]
In Vue 2 Vuex the nuxt context and plugins where available inside actions scoped to `this`. In nuxt 3 with this module that no longer seems available, is that correct?

**Comment by vedmant** [comment]
@alexcroox It should be available, the plugin provides `$store` for the nuxt context https://github.com/vedmant/nuxt3-vuex/blob/d833bcfc2d6655af5bec4f999ff8d041cfc00565/src/plugin.js#L17

**Comment by alexcroox** [comment]
Thanks, I meant all the other plugins being available inside vuex actions logic.

**Comment by alexcroox** [comment]
Example from the Nuxt 2 docs showing Nuxt plugins available in the store https://v2.nuxt.com/docs/directory-structure/plugins/#inject-in-root--context 
![SCR-20241008-jsnr](https://github.com/user-attachments/assets/9532ee80-c08a-453f-8ca2-880bca671913)

**Comment by alexcroox** [comment]
ah silly me, it's available if I do this instead:

```
export const actions = {
  async sendLogs({ state, commit, rootGetters }) {
    const { $api } = useNuxtApp()
  }
}
```
