### ISSUE TITLE
Error when store name contains a hyphen

### ISSUE THREAD

**Issue by guska8** [vedmant/nuxt3-vuex#17]
``#### Description

Import created by the plugin has wrong syntax when the store name contains a hyphen caracter

`store/common/modal-login-base.js`

#### Errors

`
Module parse failed: Unexpected token (3:13)                                                               friendly-errors 08:40:47
File was processed with these loaders:
 * ./node_modules/unplugin/dist/webpack/loaders/transform.js
 * ./node_modules/unplugin/dist/webpack/loaders/transform.js
 * ./node_modules/unplugin/dist/webpack/loaders/transform.js
 * ./node_modules/unplugin/dist/webpack/loaders/transform.js
 * ./node_modules/unplugin/dist/webpack/loaders/transform.js
 * ./node_modules/unplugin/dist/webpack/loaders/transform.js
 * ./node_modules/unplugin/dist/webpack/loaders/transform.js
 * ./node_modules/unplugin/dist/webpack/loaders/transform.js
 * ./node_modules/unplugin/dist/webpack/loaders/load.js
 * ./node_modules/esbuild-loader/dist/index.cjs
You may need an additional loader to handle the result of these loaders.
| import * as commonpagesVuexStore from '/home/tagplus/Desktop/tagplus_beta/nuxt3/store/common/pages.js';
| import {
>   commonmodal-login-baseVuexStore,
|   commonpagesVuexStore 
| } from "#imports"
`

**Comment by vedmant** [comment]
@guska8 Thanks, merged
