### ISSUE TITLE
Can't access store.

### ISSUE THREAD

**Issue by MetalSamurai666** [vedmant/nuxt3-vuex#2]
I'm using Nuxt 3 via composition API and your module(trying to use) and stuck at accessing store from .vue component:/
Also, sorry for writing in "Issues" coz it's not an issue actually.

**Comment by vedmant** [comment]
@SAMURAI-27 Please add some examples, or better reproduction https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz

**Comment by MetalSamurai666** [comment]
### menu.js
`export const state = () => ({
    show: false
})

export const mutations = {
    changeShow(state){
        state.show = !state.show
    }
}

export const getters = {
    getShow(state){
        return state.show
    }
}`

### header.vue
`<script setup>
import { useStore } from 'vuex'

const store = useStore()

function openMenu() {
    
    console.log('menu');
}
</script>`


here, for example, i want to change state **show** and have no idea how to access **mutation** changeShow

**Comment by vedmant** [comment]
@SAMURAI-27 Check documentation https://vuex.vuejs.org/guide/composition-api.html this is not related to this plugin
