### ISSUE TITLE
Windows Paths

### ISSUE THREAD

**Issue by Phil1216** [vedmant/nuxt3-vuex#8]
I'm developing nuxt3 on Windows with this module, and I noticed that the store wasn't working as I expected. I did some digging, and I found a problem in the following lines of code (39 and 40) in module.js
```
const pattern = '${fullStoreDir}/**/!(*.test)*+(.mjs|.ts|.js)'
const storeDefinitionFiles = (glob.sync(pattern))
```
I found that the function glob.sync did not recognize Windows paths (ie `C:\Users\...\NuxtProject\store`). I found that adding `.replace(/\\/g,'/')` on lines 39 and 45 solved the issue. I've considered making a pull request for it, but I'm not sure whether that use of replace is too big of an assumption that could break on non-Windows machines.

**Comment by vedmant** [comment]
@Phil1216 Hi, could you make a condition checking for windows os, like `process.platform === 'win32'`

**Comment by Phil1216** [comment]
Is this what you had in mind?
[nuxt3-vuex-module+1.0.12.patch](https://github.com/vedmant/nuxt3-vuex/files/13234431/nuxt3-vuex-module%2B1.0.12.patch)

**Comment by vedmant** [comment]
@Phil1216 Yes, can you add a pull request?

**Comment by Phil1216** [comment]
@vedmant Done

**Comment by vedmant** [comment]
@Phil1216 Merged
